"""MOC → HIRA receiver.

MOC module is not yet built. This file defines the contract that MOC will
call once it ships. Per D2 in the implementation plan, HIRA exposes a
shape-stable trigger surface; the caller side comes from MOC.

Usage (from a future MOC post-approval rule):

    from app.services.hira_moc_receiver import trigger_hira_review_for_moc

    review_cycles = await trigger_hira_review_for_moc(
        db, moc_id=moc.id, change_scope={
            "plant_id": moc.plant_id,
            "department_id": moc.department_id,
            "area_ids": [...],
            "equipment_ids": [...],
            "process_codes": [...],
            "hazards_introduced": [...],   # optional: hazard codes added
            "hazards_removed": [...],      # optional: hazard codes removed
            "implementation_date": moc.target_implementation_date,
        }
    )

Returns a list of HiraReviewCycle ids created.

Match logic (mirrors the incident-triggered rule, broader):
  - Find ACTIVE studies at change_scope.plant_id whose scope overlaps
    the change (department, area, equipment, or process).
  - For each matching HiraEntry, create a SCHEDULED HiraReviewCycle with
    triggeredBy='MOC' and triggerReferenceId=moc_id.
  - Due date: implementation_date if provided, else now + 30 days.
  - Skip entries with an open review cycle (debounce).
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any, TypedDict

from sqlalchemy import or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.hira import HiraEntry, HiraReviewCycle, HiraStudy


class MocChangeScope(TypedDict, total=False):
    plant_id: str
    department_id: str | None
    area_ids: list[str]
    equipment_ids: list[str]
    process_codes: list[str]
    hazards_introduced: list[str]
    hazards_removed: list[str]
    implementation_date: datetime | None


async def trigger_hira_review_for_moc(
    db: AsyncSession,
    moc_id: str,
    change_scope: MocChangeScope,
) -> list[str]:
    """Create HiraReviewCycle rows for entries affected by an MOC.

    No-op when MOC module is absent — the caller doesn't exist. Function
    is shape-stable so when MOC ships, only the caller needs to be wired.
    """
    plant_id = change_scope.get("plant_id")
    if not plant_id:
        return []

    department_id = change_scope.get("department_id")
    area_ids = change_scope.get("area_ids") or []
    impl_date = change_scope.get("implementation_date") or (
        datetime.now(timezone.utc) + timedelta(days=30)
    )

    # Find matching entries
    stmt = (
        select(HiraEntry, HiraStudy)
        .join(HiraStudy, HiraEntry.studyId == HiraStudy.id)
        .where(HiraStudy.plantId == plant_id)
        .where(HiraStudy.status == "ACTIVE")
        .where(HiraEntry.isCurrentVersion.is_(True))
        .where(HiraEntry.status.in_(["APPROVED", "ACTIVE", "FLAGGED_FOR_REVIEW"]))
    )

    # Narrow by department or area if provided.
    filters = []
    if department_id:
        filters.append(HiraStudy.departmentId == department_id)
    if area_ids:
        filters.append(HiraEntry.areaId.in_(area_ids))
    if filters:
        stmt = stmt.where(or_(*filters))

    rows = (await db.execute(stmt)).all()
    if not rows:
        return []

    # Debounce: skip entries with an open cycle.
    entry_ids = [r[0].id for r in rows]
    existing_open = (
        await db.execute(
            select(HiraReviewCycle.entryId)
            .where(HiraReviewCycle.entryId.in_(entry_ids))
            .where(HiraReviewCycle.status.in_(["SCHEDULED", "IN_PROGRESS"]))
        )
    ).scalars().all()
    debounce = set(existing_open)

    created_ids: list[str] = []
    for entry, study in rows:
        if entry.id in debounce:
            continue
        cycle = HiraReviewCycle(
            entryId=entry.id,
            scheduledFor=impl_date,
            triggeredBy="MOC",
            triggerReferenceId=moc_id,
            status="SCHEDULED",
            assignedToId=study.teamLeaderId,
            assignedRole="TEAM_LEADER",
        )
        db.add(cycle)
        entry.status = "FLAGGED_FOR_REVIEW"
        # Cycle id is generated by IdMixin default; we don't have it yet
        # before flush, so we collect after flush below.
        created_ids.append(entry.id)

    await db.flush()
    return created_ids
